### ISSUE TITLE
Can't build with Xcode 12

### ISSUE THREAD

**Issue by edbarbier** [IdeasOnCanvas/AppReceiptValidator#70]
Whenever I try to build my project that requires AppReceiptValidator I guess this error: 

On Xcode 12 (12A7208), if I build the project using with the old command line tool from Xcode 11.7, the Carthage build works but building the project in Xcode results in this error:
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler

If I update the Command Line tools to Xcode 12 (12A7208), and run 'carthage update --platform iOS', I get a failure with the following message: 

Task failed with exit code 65. ....
This usually indicates that project itself failed to compile.

From the log file: 

[....]
building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld /Users/EdouardBarbier/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/AppReceiptValidator/0.7.3/Build/Intermediates.noindex/AppReceiptValidator.build/Release-iphonesimulator/AppReceiptValidator\ iOS.build/Objects-normal/arm64/Binary/AppReceiptValidator normal arm64
(1 failure)

Any idea how we can get this fixed? 
Thanks in advance and let me know if I need to provide more detais.

**Comment by hannesoid** [comment]
Hi there, please try using the branch `experiment/openSSLXCFramework` of the PR #68, which is currently our "best" attempt for Xcode 12

**Comment by edbarbier** [comment]
Thanks a lot! I managed to make it work using SPM. Carthage was still triggering build issues.

**Comment by edbarbier** [comment]
Follow up on this: using SPM to install dependencies seems to trigger run issues on physical devices with Xcode 12. As per: https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953/19

This doesn't seem related to AppReceiptValidator but I'm posting this here if it can help somebody else.

**Comment by hannesoid** [comment]
We couldn't get archiving to work with the SPM approach so far, so we currently use `carthage --no-build`, include the Xcode project in our workspace from the checkouts folder, and then link to its framework target.

**Comment by xjki** [comment]
I managed to build ABI stable build of AppReceiptValidator so that compiled framework works with newer Xcode versions without recompilation with following changes (tested with framework built with Xcode11 in the Xcode12 project):

1. Changing build settings by adding BUILD_LIBRARY_FOR_DISTRIBUTION = YES; and setting SKIP_INSTALL = NO;

2. Changing framework name to AppReceiptValidatorLib to avoid module/class name clash in swiftinterface, see https://forums.swift.org/t/frameworkname-is-not-a-member-type-of-frameworkname-errors-inside-swiftinterface/28962/2


When including (new, ABI stable) AppReceiptValidatorLib into project following changes are required:

1. Add framework to project (remove old one) and set it "Embed&Sign" in the Target-General-[Frameworks, Libraries & 
Embedded content] section (and disabling/removing  /usr/local/bin/carthage copy-frameworks step from the [Build phases]).

2. Adding extra [Build phase] script to strip out unsupported architectures from the framework when running/uploading to the AppStore to avoid AppStore upload errors. I used this script: http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/


As renaming AppReceiptValidator module/framework is breaking change I did not made a pull request, you can see modifications [in my fork](https://github.com/xjki/AppReceiptValidator/commits/ABI-stability). Let me know if I should make a pull request.

**Comment by hannesoid** [comment]
Thanks @xjki for figuring this out _and documenting_ the steps! 

- I understand correctly that this way you ignore build issues with Xcode 12, by just building with Xcode 11 but making the result usable via ABI stability?

Did you fork from master branch or from https://github.com/IdeasOnCanvas/AppReceiptValidator/pull/68 ?

To sum it up we are now elaborating in a couple of directions:
- get a package-manager variant to work with archiving (current issue: openssl module something something)
- experiment with ways to discard openssl https://github.com/IdeasOnCanvas/AppReceiptValidator/pull/71
- get an openssl to work for _all_ architectures/system-sdk pairs
- make the framework version ABI stable

My ideal solution would be to get package manager working and ideally get rid of openssl and all its caused difficulty, so we can build plain old swift code from source.

I'll also need to discuss with @weichsel and @schwmi …

**Comment by xjki** [comment]
> * I understand correctly that this way you ignore build issues with Xcode 12, by just building with Xcode 11 but making the result usable via ABI stability?

Exactly. 

> Did you fork from master branch or from #68 ?

This is fork of the mater branch.

**Comment by xjki** [comment]
Probably relevant in regard of Swift Package Manager errors in Xcode 12: https://pspdfkit.com/guides/ios/current/knowledge-base/library-not-found-swiftpm/

**Comment by hannesoid** [comment]
Could be! Allthough for us it already failed at build time (when archiving)

**Comment by KevinQuisquater** [comment]
Is `experiment/openSSLXCFramework` a work in progress? Any dangers in using this branch? And when should we go back to using the normal branch?

Thanks for your work! :-)

**Comment by hannesoid** [comment]
Hi @KevinQuisquater, we're currently using `experiment/openSSLXCFramework` #68 in production, seems to work for us. 
However it's currently not been worked on, the new strategy, and it is looking good, is `experiment/useASN1Decoder` #71
Thanks for thanking!

**Comment by KevinQuisquater** [comment]
Thank you so much for taking the time to answer!

Sorry to waste your time on this, but I'll ask just in case other people are wondering the same:
I was discussing these changes with a few friends that use AppReceiptValidator in a basic way in their app (it's the only way we have found to read the original build version, basically) and we have to admit that it's not clear what we should do.

For devs that just want the dependency to keep working like it did before, but run on iOS 14, should we pick one of the branches you mentioned above, and then keep and eye on Github because we might have to switch branches in a few months? (maybe because iOS 14 brings changes that made the previous versions not compatible anymore?)

Or is there a branch we can use that might keep being the source of "truth" for future iOS releases?

Thank you so much in advance

**Comment by hannesoid** [comment]
It's a phase of change, so my current recommendation would be to use `experiment/openSSLXCFramework` for now, as it should work for iOS.
Once we have a good solution, it will land on `main` again, at which point the `experiment` branches will be removed, this way you will learn about it, and then hopefully we are back to a more stable situation.

**Comment by KevinQuisquater** [comment]
Awesome. Thank you again!

**Comment by ClowReedd** [comment]
Hello! I had to update to xCode 12 at last today, and I had been trying to avoid that because AppReceiptValidator worked great on xCode 11.7, but I cannot make it work on xCode 12. Do you have any suggestions on how to make it work with xCode 12? Thanks in advance!

**Comment by hannesoid** [comment]
Hi @ClowReedd,

- the current recommendation would be to use the branch `experiment/openSSLXCFramework` for now, as it should work for iOS. This is what we are using in production
- we are working on the branch `experiment/useASN1Decoder` (#71) which switches everything to swift package manager and removes OpenSSL dependency, this is _the future_ and what we are currently validating, but not yet proven with production experience.

Best regards

**Comment by pwallrich** [comment]
Integrating via SPM and running on the device is working with XCode 12.5 for me.

**Comment by hannesoid** [comment]
@ClowReedd @pwallrich @KevinQuisquater @edbarbier @xjki

Just pinging you in case you might benefit from the new release (we're back to `main`) which no longer uses OpenSSL, and is SPM-only. The old branches are still around in case you need for legacy stuff.
